AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Guardfile'

Lint/EmptyClass:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false
