AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Guardfile'

Lint/EmptyClass:
  Enabled: false
